dist: xenial
language: ruby
cache: bundler
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: false
  skip-cleanup: true
  target-branch: master
  local-dir: _site
  on:
    branch: jekyll
  verbose: true
branches:
  only:
  - jekyll
