dist: xenial
language: ruby
env:
  global:
    - TEXLIVE_PATH=$TRAVIS_BUILD_DIR/vendor/texlive
    - PATH=$TEXLIVE_PATH/bin/x86_64-linux:$PATH
cache:
  bundler: true
  directories:
    - $TEXLIVE_PATH
install:
  # NOTE: this is the default `bundle install` command
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - TEXLIVE_INSTALL_PREFIX=$TEXLIVE_PATH ./travis/texlive.install
script:
  - bundle exec jekyll build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  keep-history: false
  skip-cleanup: true
  target-branch: master
  local-dir: _site
  on:
    branch: jekyll
  verbose: true
branches:
  only:
  - jekyll
