# Custom data
title:               paolobrasolin.github.io
url:                 http://paolobrasolin.github.io
baseurl:             
author:
  name:              Paolo Brasolin
  url:               https://plus.google.com/+PaoloBrasolin
  email:             paolo.brasolin@gmail.com
analytics:
  provider:          google
  google:
    object_id:       UA-34703595-2

feedless:            true

# Assets filenames
favicon:             glyph.png
stylesheets:
  - filename: normalize
  - filename: main

# Sass
sass:
  style: compressed
  sass_dir: _sass

# HTML compress
#compress_html:


# Markdown conversion
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "strikethrough", "smart"]

# Default metadata
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      stylesheets:
        - filename: blog

# posts collection
permalink: /blog/:title/
# other collections
collections:
  pages:
    output: true
    permalink: /:title/
  folia:
    output: true
    permalink: /portfolio/:title/


# See https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor, Gemfile, Gemfile.lock, build.sh]
